/*SUPPORT RE_RUN
USE SUPPORT_RUN
NOTE: RUN ONLY LINE BEFORE RUN IN SUPPORT RE_RUN
*/
CREATE DATABASE MANAGEMENT_FOOTBALL_LEAGUE
USE MANAGEMENT_FOOTBALL_LEAGUE
GO
CREATE TABLE NATION(
	FFCountryCode	VARCHAR(3),
	Continent		VARCHAR NOT NULL,
	Nname			VARCHAR(20)	NOT NULL,
	UNIQUE (Continent),
	PRIMARY KEY (FFCountryCode));

CREATE TABLE SEASON(
	HostYearCode INT,
	OpenDate	DATE	NOT NULL,
	CloseDate	DATE	NOT NULL,
	No_Team		INT		NOT NULL,
	S_FFCCode	VARCHAR(3) NOT NULL,
	PRIMARY KEY (HostYearCode),
	CONSTRAINT FK_NATION_SEASON FOREIGN KEY (S_FFCCode) REFERENCES NATION(FFCountryCode) ON DELETE CASCADE);

CREATE TABLE PARTICIPATE_IN(
	P_FFCCode VARCHAR(3)	NOT NULL,
	P_HYearCode INT	NOT NULL,
	PRIMARY KEY (P_FFCCode, P_HYearCode),
	CONSTRAINT FK_NATION_PARTICIPATE FOREIGN KEY (P_FFCCode) REFERENCES NATION(FFCountryCode) ON DELETE CASCADE,
	CONSTRAINT FK_YEAR_PARTICIPATE FOREIGN KEY (P_HYearCode) REFERENCES SEASON(HostYearCode) ON DELETE CASCADE);

CREATE TABLE SEASON_TEAM(
	TeamName	VARCHAR(20),
	T_FFCCode	VARCHAR(3) NOT NULL,
	PRIMARY KEY (TeamName),
	CONSTRAINT FK_TEAM_NATION FOREIGN KEY (T_FFCCode) REFERENCES NATION(FFCountryCode) ON DELETE CASCADE);

CREATE TABLE INCLUDE(
	I_HYearCode INT	NOT NULL,
	I_TeamName	VARCHAR(20)	NOT NULL,
	No_player	INT	NOT NULL,
	PRIMARY KEY (I_HYearCode, I_TeamName),
	CONSTRAINT FK_INCLUDE_TEAM_YEAR FOREIGN KEY (I_HYearCode) REFERENCES SEASON(HostYearCode),
	CONSTRAINT FK_INCLUDE_TEAM FOREIGN KEY (I_TeamName) REFERENCES SEASON_TEAM(TeamName) ON DELETE CASCADE);

CREATE TABLE SPONSOR(
	SpsName	VARCHAR(15),
	SpsType VARCHAR,
	PRIMARY KEY (SpsName));

CREATE TABLE SPOSOR_FOR(
	SF_Name	VARCHAR(15),
	SF_Team	VARCHAR(20),
	Finance	DECIMAL(15,2),
	PRIMARY KEY (SF_Name, SF_Team),
	CONSTRAINT FK_SPONFOR_NAME FOREIGN KEY (SF_Name) REFERENCES SPONSOR(SpsName) ON DELETE SET NULL,
	CONSTRAINT FK_SPONFOR_TEAM FOREIGN KEY (SF_Team) REFERENCES SEASON_TEAM(TeamName) ON DELETE CASCADE);

CREATE TABLE STADIUM(
	StadiumCode	VARCHAR(5),
	SName VARCHAR(20),
	Address	VARCHAR(30) NOT NULL,
	UNIQUE (SName),
	PRIMARY KEY (StadiumCode));

CREATE TABLE GATE_STADIUM(
	GateStadium	INT,
	GS_SCode	VARCHAR(5),
	PRIMARY KEY (GateStadium, GS_SCode),
	CONSTRAINT FK_GATE_STADIUM FOREIGN KEY (GS_SCode) REFERENCES STADIUM(StadiumCode) ON DELETE SET NULL);

CREATE TABLE MATCHES(
	MatchCode	VARCHAR(6),
	M_HYearCode	INT,
	TimeStart	TIME NOT NULL,
	TimeFinish	TIME NOT NULL,
	MatchDate	DATE,
	M_SCode		VARCHAR(5),
	PRIMARY KEY (MatchCode, M_HYearCode),
	CONSTRAINT FK_MATCH_YEAR FOREIGN KEY (M_HYearCode) REFERENCES SEASON(HostYearCode) ON DELETE CASCADE,
	CONSTRAINT FK_MATCH_STADIUM FOREIGN KEY (M_SCode) REFERENCES STADIUM(StadiumCode)ON DELETE SET NULL);

CREATE TABLE TEAM_MEMBER(
	MemberCode	VARCHAR(6), --NATION CODE + ROLE(EX: PLAYER IS P, COACH IS C) + STT(CAN FIX)--
	FName		VARCHAR NOT NULL,
	Minit		VARCHAR NOT NULL,
	LName		VARCHAR	NOT NULL,
	Age			INT NOT NULL,
	Gender		CHAR(1) NOT NULL,
	Nationality	VARCHAR(20) NOT NULL,
	TM_Team		VARCHAR(20) NOT NULL,
	PRIMARY KEY (MemberCode),
	CONSTRAINT FK_TEAM_IN_SEASON FOREIGN KEY (TM_Team) REFERENCES SEASON_TEAM(TeamName) ON DELETE CASCADE);

CREATE TABLE COACH(
	CoachCode VARCHAR(6),
	CoachCef	VARCHAR,
	Experience	INT,
	LeadCode	VARCHAR(6),
	C_Team		VARCHAR(20),
	PRIMARY KEY (CoachCode),
	CONSTRAINT FK_SUPER_COACH FOREIGN KEY (LeadCode) REFERENCES COACH(CoachCode),
	CONSTRAINT FK_CODE_COACH_TEAM FOREIGN KEY (CoachCode) REFERENCES TEAM_MEMBER(MemberCode),
	CONSTRAINT FK_COACH_IN_TEAM FOREIGN KEY (C_Team) REFERENCES SEASON_TEAM(TeamName) ON DELETE CASCADE);

CREATE TABLE STAFF(
	StaffCode	VARCHAR(6),
	Position	VARCHAR(15),
	PRIMARY KEY (StaffCode),
	CONSTRAINT FK_STAFF_TEAM FOREIGN KEY (StaffCode) REFERENCES TEAM_MEMBER(MemberCode) ON DELETE CASCADE);

CREATE TABLE PLAYER(
	PlayerCode	VARCHAR(6),
	Status		VARCHAR(15) NOT NULL,
	Role		VARCHAR(6) NOT NULL,
	ShirtNum	INT NOT NULL,
	PRIMARY KEY (PlayerCode),
	CONSTRAINT FK_CODE_PLAYER_TEAM FOREIGN KEY (PlayerCode) REFERENCES TEAM_MEMBER(MemberCode) ON DELETE CASCADE);

CREATE TABLE IS_PLAYED(
	is_PlayedCode	VARCHAR(6),
	is_MatchCode	VARCHAR(6),
	is_YearCode		INT,
	Role			VARCHAR(2) NOT NULL,
	TimeIn			TIME NOT NULL,
	TimeOut			TIME NOT NULL,
	PRIMARY KEY	(is_PlayedCode, is_MatchCode, is_YearCode),
	CONSTRAINT FK_PLAYER_PLAY FOREIGN KEY (is_PlayedCode) REFERENCES PLAYER(PlayerCode) ON DELETE CASCADE,
	CONSTRAINT FK_PLAYED_RELATED FOREIGN KEY (is_MatchCode, is_YearCode) REFERENCES MATCHES(MatchCode, M_HYearCode) ON DELETE CASCADE);

CREATE TABLE CARD(
	TypeCard	CHAR(1), --RED = R, YELLOW = Y
	Time		TIME NOT NULL,
	Card_Player	VARCHAR(6) NOT NULL,
	Card_Match	VARCHAR(6) NOT NULL,
	Card_HYear	INT NOT NULL,
	PRIMARY KEY (TypeCard, Time, Card_Player, Card_Match, Card_HYear),
	CONSTRAINT FK_CARD_RELATED FOREIGN KEY (Card_Player, Card_Match, Card_HYear) REFERENCES IS_PLAYED(is_PlayedCode,is_MatchCode, is_YearCode) ON DELETE CASCADE);

CREATE TABLE GOALS(
	TimeGoal	TIME,
	Goal_Player	VARCHAR(6) NOT NULL,
	Goal_Match	VARCHAR(6) NOT NULL,
	Goal_HYear	INT NOT NULL,
	PRIMARY KEY (TimeGoal, Goal_Player, Goal_Match, Goal_HYear),
	CONSTRAINT FK_GOAL_RELATED FOREIGN KEY (Goal_Player, Goal_Match, Goal_HYear) REFERENCES IS_PLAYED(is_PlayedCode,is_MatchCode, is_YearCode) ON DELETE CASCADE);

CREATE TABLE ASSITS(
	TimeAssit	TIME,
	Assit_Player	VARCHAR(6) NOT NULL,
	Assit_Match		VARCHAR(6) NOT NULL,
	Assit_HYear		INT NOT NULL,
	PRIMARY KEY (TimeAssit, Assit_Player, Assit_Match, Assit_HYear),
	CONSTRAINT FK_ASSIT_RELATED FOREIGN KEY (Assit_Player, Assit_Match, Assit_HYear) REFERENCES IS_PLAYED(is_PlayedCode,is_MatchCode, is_YearCode) ON DELETE CASCADE);

CREATE TABLE PLAY_IN(
	TeamPlay	VARCHAR(20) NOT NULL,
	MatchPlay	VARCHAR(6) NOT NULL,
	HYearPlay	INT NOT NULL,
	PRIMARY KEY (TeamPlay, MatchPlay, HYearPlay),
	CONSTRAINT FK_TEAM_PLAY FOREIGN KEY (TeamPlay) REFERENCES SEASON_TEAM(TeamName) ON DELETE CASCADE,
	CONSTRAINT FK_PLAY_RELATED FOREIGN KEY (MatchPlay, HYearPlay) REFERENCES MATCHES(MatchCode, M_HYearCode) ON DELETE CASCADE);